/**
 * Created by fulle on 2025/07/04.
 */
export const EVENTS = {
    USER_LOGGED_IN: 'USER_LOGGED_IN',
    LOADING_SHOW: 'LOADING_SHOW',
    LOADING_HIDE: 'LOADING_HIDE',
    REGISTRATION_FORM_SHOW: 'REGISTRATION_FORM_SHOW',
    LOGIN_FORM_SHOW: 'LOGIN_FORM_SHOW',
    ERROR_MESSAGE_SHOW: 'ERROR_MESSAGE_SHOW',
    NOTIFICATION_SHOW: 'NOTIFICATION_SHOW',
    // Add other events here
};